### ISSUE TITLE
control_class does not work with date_select

### ISSUE THREAD

**Issue by Crazyguy** [bootstrap-ruby/rails-bootstrap-forms#350] opened 2017-10-11 08:15 UTC
Hi,

I'm trying to use control_class with date_select but it seems that the date helper is dropping that information from the controls.

```<%= f.date_select :deletion_time, label_class: 'display-none', control_class: 'display-none' %>```

Label control work ok but control class doesn't seem to get into the HTML:

```<div class="rails-bootstrap-forms-date-select"
<select id="service_deletion_time_1i" name="service[deletion_time(1i)]" class="form-control">
...
```

I am using the bootstrap-v4 branch

**Comment by mattbrictson** [comment] 2018-01-13 05:08
Closing as duplicate of #347

**Closed by mattbrictson** 2018-01-13 05:08 UTC
