### ISSUE TITLE
disable form-group wrapper in horizontal form

### ISSUE THREAD

**Issue by DSalko** [bootstrap-ruby/rails-bootstrap-forms#206] opened 2015-03-07 03:17 UTC
Hello

I wonder if it's possible to disable `form-group` wrapper for some fields. I'm building horizontal form and want to put two text fields in one line. I can change `label_col` and `control_col`, but that doesn't make any sense with wrapper form-group in place.

```
<div class='row'>
<%= form.text_field :start_date, control_col: "col-sm-3"  %>
<%= form.text_field :end_date, control_col: "col-sm-3", label_col: "col-sm-3" %>
</div>
```

Any suggestions? Thanks.

**Comment by datWav** [comment] 2015-04-24 01:14
I think at this point this is not possible. The only idea I have is to skip the libary and do this on you own.

**Comment by ohru** [comment] 2017-03-15 15:01
+1

**Comment by mattbrictson** [comment] 2017-03-15 15:45
Is this the same feature request as #89? If so I will close this as a duplicate and we can move the discussion there.

**Comment by mattbrictson** [comment] 2018-01-13 04:49
Closed as likely duplicate of #89

**Closed by mattbrictson** 2018-01-13 04:49 UTC
