### ISSUE TITLE
Collection checkbox with custom ID

### ISSUE THREAD

**Issue by StephaneMartignier** [bootstrap-ruby/rails-bootstrap-forms#349] opened 2017-10-03 07:48 UTC
Hi,

Si, i'm having the following issue :
https://stackoverflow.com/questions/46526866/rails-bootstrap-form-collection-checkbox

Basicaly : when setting custom ID for checkbox, the 'for' attribute of the label doesn't take the custom ID (related in [342](https://github.com/bootstrap-ruby/rails-bootstrap-forms/issues/342) )

Is there a way to set the 'for' attribute?

Thanks

**Comment by duleorlovic** [comment] 2017-12-05 11:39
If #357 is merged, than you can use `id` option to set `custom_id` and it will be used as checkbox `id` and label `for` attribute.
Look for example test case

https://github.com/duleorlovic/rails-bootstrap-forms/blob/label_for_attribute/test/bootstrap_checkbox_test.rb#L35-L38

**Comment by mattbrictson** [comment] 2018-01-13 05:08
Closing as duplicate of #342

**Closed by mattbrictson** 2018-01-13 05:08 UTC
